#!/bin/bash

GR='\033[1;32m'
NC='\033[0m'

# Build sometimes runs into trouble with Eigen library, I attempted a fix below but it does not always work.
# Run sudo ln -s (PATH_TO_EIGEN_LIB) /usr/include/Eigen if include path cannot be found.
EIGEN=/usr/include/Eigen
[ -f $EIGEN ] || (echo 'Adding Eigen symbolic link prior to install.' && sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen)

# Install script
Version=$1
echo -e "${GR}Starting OpenCV install. Removing previous files and checking dependencies.${NC}"
sudo rm -R opencv*
sudo apt install build-essential cmake git pkg-config libgtk-3-dev
sudo apt install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libxvidcore-dev libx264-dev
sudo apt install libjpeg-dev libpng-dev libtiff-dev gfortran openexr libatlas-base-dev
sudo apt install python3-dev python3-numpy libtbb2 libtbb-dev libdc1394-22-dev
mkdir ~/opencv_build && cd ~/opencv_build
git clone https://github.com/opencv/opencv.git && cd opencv
git checkout $Version
cd .. && git clone https://github.com/opencv/opencv_contrib.git && cd opencv_contrib
git checkout $Version
cd ~/opencv_build/opencv
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=ON \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_GENERATE_PKGCONFIG=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules \
    -D BUILD_EXAMPLES=ON ..
echo -e "${GR}Starting build of OpenCV with $(nproc) cores.${NC}"
make -j$(nproc)
sudo make install
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
echo -e "${GR}Script complete. Verify installation version below.${NC}"
pkg-config --modversion opencv${Version:0:1}